#ifndef TOKEN_TYPES_H
#define TOKEN_TYPES_H


enum class TokenTypes {COMMA,PERIOD,Q_MARK,LEFT_PAREN,RIGHT_PAREN,COLON,COLON_DASH,MULTIPLY,ADD,SCHEMES,FACTS,RULES,QUERIES,ID,STRING,COMMENT,UNDEFINED, END_OF_FILE };


#endif // !TOKEN_TYPES_H

